### ISSUE TITLE
Failed to execute 'removeEventListener'

### ISSUE THREAD

**Issue by sljcb** [ftes/react-dual-timeline#1]
Hi Fredrik,

I really love your react-dual-timeline module. Thank you so much for making it. 
When I try to use it, got the error when I try to leave the current page.
`uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.`
<img width="531" alt="screen shot 2017-02-07 at 11 59 16 pm" src="https://cloud.githubusercontent.com/assets/5875430/22728193/768bcc56-ed91-11e6-984c-41054dd378a2.png">
Could you please fix it? 
Thanks,

Ran

**Comment by ftes** [comment]
Hi, thanks for the feedback :)
I commited a fix and published a new version to npm (0.2.6) which should fix this issue.

**Comment by ftes** [comment]
Sorry, misread the error message at first.
v0.2.7 should now really fix it

**Comment by sljcb** [comment]
Hi Fredrik,
Thanks for putting up a fix. But I forget to add one more screenshot for the issue.
<img width="866" alt="screen shot 2017-02-08 at 9 22 01 am" src="https://cloud.githubusercontent.com/assets/5875430/22748822/37dea056-ede0-11e6-9ce6-18984be875a9.png">
It seems that the removeEventLinstenr requires two arguments.

Thanks,
Ran

**Comment by ftes** [comment]
The new version does not use removeEventListener any more:
https://github.com/ftes/react-dual-timeline/blob/c9aaf9c16f8c4ea2c017327bf0dd078a384a0c75/src/timeline.js#L38

Are you still using an old version?

**Comment by sljcb** [comment]
You're right, I forgot to compile my code.
It works now! Thank you so much!
